dist: bionic

language: java

addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt install openjdk-8-jdk openjdk-8-jre
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - java -version
  - sudo apt-get install python3 python3-pip python3-setuptools
  - python3 -m pip install -U pip
  - pip3 install --user -r psl-python/requirements.txt

before_script:
  - createdb psltest

script:
  - mvn integration-test -B
  - ./.ci/deploy-docs.sh
